### ISSUE TITLE
Control appearing above others.

### ISSUE THREAD

**Issue by ramblerswebs** [jjimenezshaw/Leaflet.Control.Resizer#2]
Firstly thanks for a great plugin.
I have found that if I place a map control in the bottom left position then the resize control is displayed above this control so that one cannot click on it.
On inspection I see your css has the statement z-index: 1000.
Other controls seem to be set with z-index 800
As the resize control at the bottom extends to the left and right of the map I have had to set the z-index to 750 so that the bottom left control works.
I hope this makes sense.
I don't know if my solution is a good one or could the bottom resizer be smaller in width.

**Comment by ramblerswebs** [comment]
Just to say that as I just use the control on the bottom of the map I have ended up just adding this css rather than changing the z-index value
div.leaflet-control-container div.leaflet-control-resizer-corner-s{
    width:50px;
    left:50%;
}

**Comment by jjimenezshaw** [comment]
The prevalence (z-index) of the controls... can be problematic. The good thing is that you can always overwrite the css styles.
