### ISSUE TITLE
Minimum map size

### ISSUE THREAD

**Issue by ramblerswebs** [jjimenezshaw/Leaflet.Control.Resizer#3]
Not sure if you are still supporting this project but in case you are it would be good to be able to supply a minimum size for the map so the user cannot resizer to a smaller size than this.

**Comment by jjimenezshaw** [comment]
Hi @ramblerswebs . it is stable, but not dead ;)
Is it enough setting css styles like `min-width` and `min-height`? it seems to work for me.

**Comment by ramblerswebs** [comment]
Thanks
I ended up with this code
  this.controls.resizer.addEventListener('drag', function () {
        var newHeight = self._mapDiv.clientHeight;
        if (newHeight < self.minHeight) {
            self._mapDiv.style.height = self.minHeight + "px";
            //  only allow map to be larger
        }

    });

**Comment by jjimenezshaw** [comment]
I tried `css` styles `min-width` and `min-height` in both Chrome and Firefox, and both work (for future readers).
